---
# yamllint disable rule:line-length
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude_types: [python, javascript, dtd, markdown, makefile, xml]
        exclude: binary|\.bin$
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/jameswoolfenden/pre-commit
    rev: v0.1.36
    hooks:
      - id: terraform-fmt
      - id: tf2docs
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.400
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d examples
