---
# yamllint disable rule:indentation
site_name: Learn Packer
nav:
  - Home: index.md
  - Installing: installing-packer.md
  - AWS AMI: packer-aws-ami.md
  - Advanced AWS authentication: packer-aws-ami.2.md
  - Versioning: packer-aws-ami.3.md
  - Docker:
      - docker: docker.md
      - docker-hcl: docker-hcl2.md
  - Ansible-Docker: ansible-docker.md
  - File: packer-file.md
  - ISO: packer-iso.md
  - NULL: packer-null.md
  - Post-processor: post-processor.md
  - Variables: variables.md
  - Extending: extending.md
  - Imagebuilder: imagebuilder.md
  - Functions: functions.md
  - HCL2: hcl2.md
  - Sharing: share.md
  - Help: help.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  favicon: "assets/images/favicon.ico"

repo_name: "jamesWoolfenden/learn-packer"
repo_url: "https://github.com/jamesWoolfenden/learn-packer"

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-add-teaser:
      teaser_class: "teaser"
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/jameswoolfenden"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/JimWoolfenden"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/jameswoolfenden/"

# Copyright
copyright: "Copyright &copy; 2019 - 2021 James Woolfenden"
site_author: "James Woolfenden"
google_analytics: ["UA-151885688-2", "jameswoolfenden.github.io/learn-packer/"]
