site_name: Learn Packer
nav:
    - Home: index.md
    - Installing: installing-packer.md
    - AWS AMI: packer-aws-ami.md
    - Advanced AWS authentication: packer-aws-ami.2.md
    - Versioning: packer-aws-ami.3.md
    - Docker: docker.md
    - Ansible-Docker: ansible-docker.md
    - File: packer-file.md
    - ISO: packer-iso.md
    - NULL: packer-null.md
    - Post-processor: post-processor.md
    - Variables: variables.md
    - About: about.md
theme: readthedocs